### ISSUE TITLE
headlong-bookmark-jump won't work after restarting emacs

### ISSUE THREAD

**Issue by jagrg** [abo-abo/headlong#1]
It seems that `headlong-bookmark-jump` only works if some bookmark function is called before. For example, if I restart emacs and call say `bookmark-bmenu-list`, then `headlong-bookmark-jump` becomes functional, even after the bookmark list buffer is killed, otherwise it won't work.

**Comment by abo-abo** [comment]
Here's my bookmark setup:

``` el
(require 'bookmark)
(setq bookmark-completion-ignore-case nil)
(bookmark-maybe-load-default-file)
```

I think it's `bookmark-maybe-load-default-file` that prevents me from getting a problem.

**Comment by jagrg** [comment]
Indeed, `bookmark-maybe-load-default-file` fixed it.

**Comment by abo-abo** [comment]
OK, I don't think that `bookmark-maybe-load-default-file` should be in `headlong`, since it takes
some time to run and the user should configure her own bookmarks the way that she wants.
