### ISSUE TITLE
Adding bookmark shortcuts

### ISSUE THREAD

**Issue by jagrg** [abo-abo/headlong#2]
I [see](http://oremacs.com/2015/01/06/rushing-headlong/) you have letters associated with your bookmarks, like `i: init.el`, but I'm not sure how you got that. Could you maybe describe the process?

**Comment by abo-abo** [comment]
1. Call `bookmark-bmenu-list`.
2. Call `bookmark-bmenu-rename`. It's bound to <kbd>r</kbd>, I think.

That's it, this is just a naming convention for my bookmarks.
