### ISSUE TITLE
Remembering position

### ISSUE THREAD

**Issue by jagrg** [abo-abo/headlong#3]
Instead of using `bmkp-bookmark-set-confirm-overwrite` to relocate my position in the buffer, it would be nice if there was an option for saving it automatically, similar to [Save Place](http://www.emacswiki.org/emacs/SavePlace). Any thoughts?

**Comment by abo-abo** [comment]
I don't see how this is related to `headlong`. Both `bookmark+` and `save-place` are orthogonal to this package.

**Comment by jagrg** [comment]
I was thinking of `headlong-bookmark-jump`, but you are right, it's more of a `bookmark+` issue. Sorry for the noise.

**Comment by abo-abo** [comment]
No problem, you can ask about bookmark+ [here](http://emacs.stackexchange.com/questions).
